services:
  tailscale:
    hostname: ${TAILNET_NAME}
    image: tailscale/tailscale
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      - ./ts-serve.json:/config/ts-serve.json:ro
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_SERVE_CONFIG: /config/ts-serve.json
      TS_AUTH_ONCE: true
      TS_STATE_DIR: /var/lib/tailscale
      TS_HOST: ${TAILNET_NAME}
    restart: unless-stopped
    networks:
      - freshrss

  freshrss:
    image: freshrss/freshrss:1.26.1
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/data:/var/www/FreshRSS/data
      - ./data/extensions:/var/www/FreshRSS/extensions 
    environment:
      TZ: America/Los_Angeles
      CRON_MIN: '3,33'
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --db-base ${DB_BASE}
        --db-host localhost
        --db-password ${DB_PASSWORD}
        --db-type pgsql
        --db-user ${DB_USER}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user ${ADMIN_USERNAME}
    network_mode: service:tailscale              

  postgres:
    image: postgres:17
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE:-freshrss}
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}
    network_mode: service:tailscale

networks:
  freshrss:
    name: freshrss
