services:
  freshrss:
    image: freshrss/freshrss:1.26.1
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/data:/var/www/FreshRSS/data
      - ./data/extensions:/var/www/FreshRSS/extensions
    ports:
      - "8040:80"      
    environment:
      TZ: America/Los_Angeles
      CRON_MIN: '3,33'
      FRESHRSS_INSTALL: |-
        --api-enabled
        --base-url ${BASE_URL}
        --db-base ${DB_BASE}
        --db-host ${DB_HOST}
        --db-password ${DB_PASSWORD}
        --db-type pgsql
        --db-user ${DB_USER}
        --default-user admin
        --language en
      FRESHRSS_USER: |-
        --api-password ${ADMIN_API_PASSWORD}
        --email ${ADMIN_EMAIL}
        --language en
        --password ${ADMIN_PASSWORD}
        --user ${ADMIN_USERNAME}        

  postgres:
    image: postgres:17
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_BASE:-freshrss}
      POSTGRES_USER: ${DB_USER:-freshrss}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-freshrss}